//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credenciales
    {
        public int Pais { get; set; }
        public int Tdoc { get; set; }
        public string Ndoc { get; set; }
        public string Usuario { get; set; }
        public string Contra { get; set; }
        public int Rol { get; set; }
        public string Email { get; set; }
        public System.DateTime FecAlt { get; set; }
        public Nullable<System.DateTime> FecUltAcc { get; set; }
        public Nullable<System.DateTime> FecUltMod { get; set; }
    }
}
