//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPJ01
    {
        public int Pais { get; set; }
        public int Tdoc { get; set; }
        public string Ndoc { get; set; }
        public string RazSoc { get; set; }
        public Nullable<int> TipoEnt { get; set; }
        public string PagWeb { get; set; }
    }
}
