//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guardar_Ofertas
    {
        public string Codigo_Usu { get; set; }
        public int Id_Oferta { get; set; }
        public Nullable<System.DateTime> Fecha_Guardado { get; set; }
    }
}
