//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class message_chat
    {
        public int Id { get; set; }
        public int Id_Chat { get; set; }
        public int PaisEmisor2 { get; set; }
        public int TdocEmisor2 { get; set; }
        public string NdocEmisor2 { get; set; }
        public int PaisReceptor2 { get; set; }
        public int TdocReceptor2 { get; set; }
        public string NdocReceptor2 { get; set; }
        public string Mensaje { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Leido { get; set; }
    }
}
