//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ofertas
    {
        public int Id { get; set; }
        public int Tipo_Oferta { get; set; }
        public Nullable<int> Pais { get; set; }
        public Nullable<int> Tdoc { get; set; }
        public string Ndoc { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Categoria { get; set; }
        public string Foto { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> FechaPubl { get; set; }
    }
}
