//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        public int Pais { get; set; }
        public int Tdoc { get; set; }
        public string Ndoc { get; set; }
        public string Tipo { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Provincia { get; set; }
        public Nullable<int> Localidad { get; set; }
        public Nullable<int> Barrio { get; set; }
        public Nullable<int> Rol { get; set; }
        public Nullable<int> Tipo_Domicilio { get; set; }
        public string Domicilio { get; set; }
        public string Telefono { get; set; }
        public string Telefono_aux { get; set; }
        public string Email { get; set; }
    }
}
